<a href="https://colab.research.google.com/github/smbonilla/learningPyTorch/blob/main/00_pyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

### Resource notebook: https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb



In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.tensor()' = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar 
scalar = torch.tensor(7) 
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# Matrix 
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([7, 8])

In [15]:
MATRIX[0][0]

tensor(7)

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# Tensor 
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors 

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data. 

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [23]:
# Creating a random tensor of size (3,4)

randomTensor = torch.rand(3,4)
randomTensor

tensor([[0.0396, 0.8355, 0.4940, 0.3736],
        [0.0406, 0.3824, 0.5884, 0.0015],
        [0.6177, 0.8371, 0.6627, 0.9909]])

In [26]:
# Create a random tensor with similar shape to an image tensor

randomImageSizeTensor = torch.rand(size=(224,224,3)) # height, width, color channel
randomImageSizeTensor.shape, randomImageSizeTensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
# Creating random tensor with shape (7,7)

ex2 = torch.rand(7,7)
ex2

tensor([[0.6849, 0.7899, 0.1336, 0.8465, 0.8857, 0.9559, 0.9748],
        [0.8496, 0.6856, 0.8066, 0.0180, 0.3068, 0.9088, 0.4513],
        [0.2810, 0.7990, 0.8550, 0.0861, 0.6947, 0.1403, 0.7224],
        [0.9814, 0.7013, 0.3932, 0.2535, 0.9206, 0.0709, 0.2179],
        [0.0869, 0.5625, 0.2051, 0.6289, 0.4824, 0.1689, 0.4382],
        [0.9134, 0.1194, 0.7051, 0.5184, 0.3654, 0.3620, 0.4304],
        [0.3164, 0.3268, 0.4595, 0.6434, 0.7313, 0.8400, 0.6983]])

### Zeros and Ones 

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros*randomTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [46]:
# Use torch.range()

oneToTen = torch.arange(start=1, end=11, step=1)
oneToTen

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# Creating tensors like another tensor - same shape as oneToTen

tenZeros = torch.zeros_like(oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])