<a href="https://colab.research.google.com/github/smbonilla/learningPyTorch/blob/main/00_pyTorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

### Resource notebook: https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb



In [ ]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
print(torch.__version__)

1.12.1+cu113


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.tensor()' = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar 
scalar = torch.tensor(7) 
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix 
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[0][0]

tensor(7)

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor 
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors 

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data. 

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Creating a random tensor of size (3,4)

randomTensor = torch.rand(3,4)
randomTensor

tensor([[0.0396, 0.8355, 0.4940, 0.3736],
        [0.0406, 0.3824, 0.5884, 0.0015],
        [0.6177, 0.8371, 0.6627, 0.9909]])

In [ ]:
# Create a random tensor with similar shape to an image tensor

randomImageSizeTensor = torch.rand(size=(224,224,3)) # height, width, color channel
randomImageSizeTensor.shape, randomImageSizeTensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Creating random tensor with shape (7,7)

ex2 = torch.rand(7,7)
ex2

tensor([[0.6849, 0.7899, 0.1336, 0.8465, 0.8857, 0.9559, 0.9748],
        [0.8496, 0.6856, 0.8066, 0.0180, 0.3068, 0.9088, 0.4513],
        [0.2810, 0.7990, 0.8550, 0.0861, 0.6947, 0.1403, 0.7224],
        [0.9814, 0.7013, 0.3932, 0.2535, 0.9206, 0.0709, 0.2179],
        [0.0869, 0.5625, 0.2051, 0.6289, 0.4824, 0.1689, 0.4382],
        [0.9134, 0.1194, 0.7051, 0.5184, 0.3654, 0.3620, 0.4304],
        [0.3164, 0.3268, 0.4595, 0.6434, 0.7313, 0.8400, 0.6983]])

### Zeros and Ones 

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*randomTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()

oneToTen = torch.arange(start=1, end=11, step=1)
oneToTen

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like another tensor - same shape as oneToTen

tenZeros = torch.zeros_like(oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

***Note:*** Tensory datatypes is one of the 3 biggest errors you might run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float32Tensor = torch.tensor([3.0, 6.0, 9.0], 
                             dtype = None, # what datatype tensor is 
                             device = None, # by default device="cpu" 
                             requires_grad=False) # track gradients as tensor goes through operations 
float32Tensor

tensor([3., 6., 9.])

In [ ]:
float32Tensor.dtype

torch.float32

In [ ]:
float16Tensor = float32Tensor.type(torch.float16) # change data type
float16Tensor 

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float16Tensor*float32Tensor

tensor([ 9., 36., 81.])

In [ ]:
int32Tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int32Tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a random tensor

someTensor = torch.rand([3,4])
someTensor

tensor([[0.2655, 0.6278, 0.2500, 0.6135],
        [0.8087, 0.5547, 0.5962, 0.8198],
        [0.4740, 0.1925, 0.4861, 0.6150]])

In [ ]:
# Find out details about some tensor

print(someTensor)
print(f"Datatype of tensor: {someTensor.dtype}")
print(f"Shape of tensor: {someTensor.shape}") # can use someTensor.size() or someTensor.shape
print(f"Device tensor is on: {someTensor.device}")

tensor([[0.2655, 0.6278, 0.2500, 0.6135],
        [0.8087, 0.5547, 0.5962, 0.8198],
        [0.4740, 0.1925, 0.4861, 0.6150]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* addition
* subtraction
* multiplication (element-wise)
* division
* matrix multiplication 

In [ ]:
# addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiplication

tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtraction

tensor - 10

tensor([ 90, 190, 290])

In [ ]:
# try out PyTorch in-built functions

torch.mul(tensor,10), torch.add(tensor,10), torch.sub(tensor,10)

(tensor([1000, 2000, 3000]), tensor([110, 210, 310]), tensor([ 90, 190, 290]))

### Matrix Multiplication

two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication 
2. Matrix multiplication (dot product)

There are two main rules for performing matrix multiplication: 
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions** 

In [ ]:
# Element-wise multiplication 
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### Shape Errors

In [ ]:
# shapes for matrix multiplication 

tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensorA,tensorB.T) # torch.mm is the same as torch.matmul 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensorB.T, tensorB.T.shape # transpose tensor

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor

x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# find the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean - note: the torch.mean() fun requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# find position of max 

torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
# find position of min

torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

### Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape 
* View - return a view of an input tensor of certain shape but keep same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (Swapped) in a certain way 

In [ ]:
# create a tensor 

x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension

xReshaped = x.reshape(9,1)
xReshaped, xReshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [ ]:
# change the view 

z = x.view(9,1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)

z[0,:] = 5
z,x

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other

xStacked = torch.stack([x, x, x, x], dim = 1)
xStacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# squeeze tensors (removes all single dimensions frmo a target tensor)

xSqueeze = xReshaped.T.squeeze()

xReshaped.T.squeeze().shape, xReshaped.T.shape

(torch.Size([9]), torch.Size([1, 9]))

In [ ]:
# unsqueeze tensors (adds a single dimension to a target tensor at a specific dim)

xUnsqueeze = xSqueeze.unsqueeze(dim=0)
xUnsqueeze, xUnsqueeze.shape

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]), torch.Size([1, 9]))

In [ ]:
# permute - torch.permute rearranges the dimensions of a target tensor - returns a view

xOriginal = torch.rand(size=(224, 224, 3)) # [height, width, colorChannels]

# permute original tensor to rearrange the axis (or dim) order 

xPermute = torch.permute(xOriginal, [2, 0 , 1]) # or xOriginal.permute(2,0,1)

print(f"Previous shape: {xOriginal.shape}")
print(f"Previous shape: {xPermute.size()}") # if you change xPermute, it changes xOriginal as well

Previous shape: torch.Size([224, 224, 3])
Previous shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

indexing with PyTorch is similar to indexing with Numpy. 

In [ ]:
# Create a tensor

x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
# Index on our new tensor

x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [ ]:
# get number 9 

x[0][2][2], x[:,2,2]

(tensor(9), tensor([9]))

In [ ]:
# get all values of 0th and 1st dim but only index 1 of 2nd dim

x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of 0 dimension but only 1 index of 1st and 2nd dim

x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dim

x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# get 3,6,9

x[:,:,2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy 

Numpy is a popular scientific Python numerical computing library - PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor, want Numpy -> `torch.Tensor.numpy()`


In [ ]:
# numpy array to tensor 

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # if you want torch.from_numpy(array).dtype(float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the value of the array, what will this do to the `tensor`?

array = array + 1 

tensor # tensor does not change

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
# tensor to NumPy array 

tensor = torch.ones(7)
numpyTensor = tensor.numpy()
tensor, numpyTensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**. 

Essentually what the random seed does is "flavour" the randomness. 

In [ ]:
# create two random tensors

randA = torch.rand(3,4)
randB = torch.rand(3,4)

print(randA)
print(randB)
print(randA == randB)

tensor([[0.7131, 0.7484, 0.9672, 0.4200],
        [0.5483, 0.7565, 0.5915, 0.0044],
        [0.5854, 0.6305, 0.7533, 0.9427]])
tensor([[0.1331, 0.9609, 0.6403, 0.0578],
        [0.7206, 0.9557, 0.9212, 0.6507],
        [0.8561, 0.7665, 0.5256, 0.3988]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensors 

# set random seed 
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
randC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randD = torch.rand(3,4)

print(randC)
print(randD)
print(randC == randD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUS = faster computation on numbers, thanks to CUDA + NVIDIA hardware +PyTorch working behind the scenes making everything nice



### 1. Getting a GPU

1. Easiest - Use google colab for a free GPU (options to upgrade)
2. Get your own GPU - requires set up and investment - The best GPUS for deep learning 2020 timm dettmers
3. Use cloud computing - GCP, AWS, Azure, digital oceans, services allow you to rent computers on the cloud



### 2. Check for GPU access with PyTorch

In [ ]:
# check for GPU access with PyTorch --> change runtime type

import torch 
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code --> run on GPU if available, else default to CPU 

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of GPUS !nvidia-smi

torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# create a tensor (default on the cpu)

tensor = torch.tensor([1, 2, 3])

# tensor not on GPU 
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU (if available)

tensorOnGpu = tensor.to(device)
tensorOnGpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU 

NumPy only works in CPU 

In [ ]:
# to fix GPU tensor with NumPy issue, first set it to CPU
tensorOnCpu = tensorOnGpu.cpu().numpy()
tensorOnCpu

array([1, 2, 3])

In [ ]:
tensorOnGpu

tensor([1, 2, 3], device='cuda:0')